### ISSUE TITLE
There is no ScreenControl.unitypackage

### ISSUE THREAD

**Issue by trungchubao** [ultraleap/ScreenControl#21]
Hi!
I'm trying to import the package into my own Unity project as guided in the README in ScreenControl/ScreenControl/. But I can't find ScreenControl.unitypackage. Should I build the package on my end provided the source code from this repository?

**Comment by Ultraleap-Dan** [comment]
Hi,

We do not currently have a public release available for Screen Control, to make this ready to import into your Unity Project you would need to generate your own build after forking the repository and then building from the correct (develop) branch.
Please remember that unless it is an officially released application available from our website or an explicitly agreed license. It is not supported by Ultraleap and we are not responsible for anything that you create.

To get started, you will need to build the ScreenControlService scene, which is at 'Assets/ScreenControl/Service/Scenes’. You will then need to export ONLY the 'Assets/ScreenControl/Client' folder as a package and import it into your own project.
Please be aware that there is a known issue where the 'RingCursor' in the client prefab defaults the 'ringThickness' to 0 and it should be 2.

We are interested to hear more about your project and what you are looking to use Screen Control to create. Please can you send us some details to support@ultraleap.com and we can see if there is any advice or guidance that we can provide?

**Comment by trungchubao** [comment]
Understood! Thank you so much for your kind explanation. By the way, what I'm trying to do is to customize gesture recognition using a Rigel evaluation kit.
